/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as DistributorRouteRouteImport } from './routes/_distributor/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as UpdatePasswordRouteImport } from './routes/update-password'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedReferralsRouteImport } from './routes/_authenticated/referrals'
import { Route as OrderOrderNumberRouteImport } from './routes/order.$orderNumber'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminCouponsRouteImport } from './routes/_authenticated/admin.coupons'
import { Route as AuthenticatedAdminCustomersRouteImport } from './routes/_authenticated/admin.customers'
import { Route as AuthenticatedAdminDistributorsRouteImport } from './routes/_authenticated/admin.distributors'
import { Route as AuthenticatedAdminInventoryRouteImport } from './routes/_authenticated/admin.inventory'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin.orders'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin.products'
import { Route as AuthenticatedAdminProductsBoardRouteImport } from './routes/_authenticated/admin.products-board'
import { Route as AuthenticatedAdminReferralsRouteImport } from './routes/_authenticated/admin.referrals'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as DistributorDistributorIndexRouteImport } from './routes/_distributor/distributor.index'
import { Route as DistributorDistributorInventoryRouteImport } from './routes/_distributor/distributor.inventory'
import { Route as DistributorDistributorOrdersRouteImport } from './routes/_distributor/distributor.orders'
import { Route as DistributorDistributorRequestsRouteImport } from './routes/_distributor/distributor.requests'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const DistributorRouteRoute = DistributorRouteRouteImport.update({
  id: '/_distributor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatePasswordRoute = UpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReferralsRoute = AuthenticatedReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const OrderOrderNumberRoute = OrderOrderNumberRouteImport.update({
  id: '/order/$orderNumber',
  path: '/order/$orderNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCouponsRoute =
  AuthenticatedAdminCouponsRouteImport.update({
    id: '/coupons',
    path: '/coupons',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCustomersRoute =
  AuthenticatedAdminCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDistributorsRoute =
  AuthenticatedAdminDistributorsRouteImport.update({
    id: '/distributors',
    path: '/distributors',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInventoryRoute =
  AuthenticatedAdminInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProductsBoardRoute =
  AuthenticatedAdminProductsBoardRouteImport.update({
    id: '/products-board',
    path: '/products-board',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReferralsRoute =
  AuthenticatedAdminReferralsRouteImport.update({
    id: '/referrals',
    path: '/referrals',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const DistributorDistributorIndexRoute =
  DistributorDistributorIndexRouteImport.update({
    id: '/distributor/',
    path: '/distributor/',
    getParentRoute: () => DistributorRouteRoute,
  } as any)
const DistributorDistributorInventoryRoute =
  DistributorDistributorInventoryRouteImport.update({
    id: '/distributor/inventory',
    path: '/distributor/inventory',
    getParentRoute: () => DistributorRouteRoute,
  } as any)
const DistributorDistributorOrdersRoute =
  DistributorDistributorOrdersRouteImport.update({
    id: '/distributor/orders',
    path: '/distributor/orders',
    getParentRoute: () => DistributorRouteRoute,
  } as any)
const DistributorDistributorRequestsRoute =
  DistributorDistributorRequestsRouteImport.update({
    id: '/distributor/requests',
    path: '/distributor/requests',
    getParentRoute: () => DistributorRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/update-password': typeof UpdatePasswordRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/orders': typeof AuthenticatedOrdersRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/order/$orderNumber': typeof OrderOrderNumberRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/distributors': typeof AuthenticatedAdminDistributorsRoute
  '/admin/inventory': typeof AuthenticatedAdminInventoryRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/products-board': typeof AuthenticatedAdminProductsBoardRoute
  '/admin/referrals': typeof AuthenticatedAdminReferralsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/distributor/inventory': typeof DistributorDistributorInventoryRoute
  '/distributor/orders': typeof DistributorDistributorOrdersRoute
  '/distributor/requests': typeof DistributorDistributorRequestsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/distributor/': typeof DistributorDistributorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/update-password': typeof UpdatePasswordRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/order/$orderNumber': typeof OrderOrderNumberRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/distributors': typeof AuthenticatedAdminDistributorsRoute
  '/admin/inventory': typeof AuthenticatedAdminInventoryRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/products-board': typeof AuthenticatedAdminProductsBoardRoute
  '/admin/referrals': typeof AuthenticatedAdminReferralsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/distributor/inventory': typeof DistributorDistributorInventoryRoute
  '/distributor/orders': typeof DistributorDistributorOrdersRoute
  '/distributor/requests': typeof DistributorDistributorRequestsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/distributor': typeof DistributorDistributorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_distributor': typeof DistributorRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/update-password': typeof UpdatePasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/referrals': typeof AuthenticatedReferralsRoute
  '/order/$orderNumber': typeof OrderOrderNumberRoute
  '/product/$slug': typeof ProductSlugRoute
  '/_authenticated/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/_authenticated/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/_authenticated/admin/distributors': typeof AuthenticatedAdminDistributorsRoute
  '/_authenticated/admin/inventory': typeof AuthenticatedAdminInventoryRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRoute
  '/_authenticated/admin/products-board': typeof AuthenticatedAdminProductsBoardRoute
  '/_authenticated/admin/referrals': typeof AuthenticatedAdminReferralsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_distributor/distributor/inventory': typeof DistributorDistributorInventoryRoute
  '/_distributor/distributor/orders': typeof DistributorDistributorOrdersRoute
  '/_distributor/distributor/requests': typeof DistributorDistributorRequestsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_distributor/distributor/': typeof DistributorDistributorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/shop'
    | '/signup'
    | '/update-password'
    | '/admin'
    | '/orders'
    | '/profile'
    | '/referrals'
    | '/order/$orderNumber'
    | '/product/$slug'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/distributors'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/products-board'
    | '/admin/referrals'
    | '/admin/settings'
    | '/distributor/inventory'
    | '/distributor/orders'
    | '/distributor/requests'
    | '/admin/'
    | '/distributor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/shop'
    | '/signup'
    | '/update-password'
    | '/orders'
    | '/profile'
    | '/referrals'
    | '/order/$orderNumber'
    | '/product/$slug'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/distributors'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/products-board'
    | '/admin/referrals'
    | '/admin/settings'
    | '/distributor/inventory'
    | '/distributor/orders'
    | '/distributor/requests'
    | '/admin'
    | '/distributor'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_distributor'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/shop'
    | '/signup'
    | '/update-password'
    | '/_authenticated/admin'
    | '/_authenticated/orders'
    | '/_authenticated/profile'
    | '/_authenticated/referrals'
    | '/order/$orderNumber'
    | '/product/$slug'
    | '/_authenticated/admin/coupons'
    | '/_authenticated/admin/customers'
    | '/_authenticated/admin/distributors'
    | '/_authenticated/admin/inventory'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/products-board'
    | '/_authenticated/admin/referrals'
    | '/_authenticated/admin/settings'
    | '/_distributor/distributor/inventory'
    | '/_distributor/distributor/orders'
    | '/_distributor/distributor/requests'
    | '/_authenticated/admin/'
    | '/_distributor/distributor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  DistributorRouteRoute: typeof DistributorRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ShopRoute: typeof ShopRoute
  SignupRoute: typeof SignupRoute
  UpdatePasswordRoute: typeof UpdatePasswordRoute
  OrderOrderNumberRoute: typeof OrderOrderNumberRoute
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_distributor': {
      id: '/_distributor'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DistributorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/update-password': {
      id: '/update-password'
      path: '/update-password'
      fullPath: '/update-password'
      preLoaderRoute: typeof UpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/referrals': {
      id: '/_authenticated/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof AuthenticatedReferralsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/order/$orderNumber': {
      id: '/order/$orderNumber'
      path: '/order/$orderNumber'
      fullPath: '/order/$orderNumber'
      preLoaderRoute: typeof OrderOrderNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/coupons': {
      id: '/_authenticated/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AuthenticatedAdminCouponsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/customers': {
      id: '/_authenticated/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AuthenticatedAdminCustomersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/distributors': {
      id: '/_authenticated/admin/distributors'
      path: '/distributors'
      fullPath: '/admin/distributors'
      preLoaderRoute: typeof AuthenticatedAdminDistributorsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/inventory': {
      id: '/_authenticated/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AuthenticatedAdminInventoryRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/products-board': {
      id: '/_authenticated/admin/products-board'
      path: '/products-board'
      fullPath: '/admin/products-board'
      preLoaderRoute: typeof AuthenticatedAdminProductsBoardRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/referrals': {
      id: '/_authenticated/admin/referrals'
      path: '/referrals'
      fullPath: '/admin/referrals'
      preLoaderRoute: typeof AuthenticatedAdminReferralsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_distributor/distributor/': {
      id: '/_distributor/distributor/'
      path: '/distributor'
      fullPath: '/distributor/'
      preLoaderRoute: typeof DistributorDistributorIndexRouteImport
      parentRoute: typeof DistributorRouteRoute
    }
    '/_distributor/distributor/inventory': {
      id: '/_distributor/distributor/inventory'
      path: '/distributor/inventory'
      fullPath: '/distributor/inventory'
      preLoaderRoute: typeof DistributorDistributorInventoryRouteImport
      parentRoute: typeof DistributorRouteRoute
    }
    '/_distributor/distributor/orders': {
      id: '/_distributor/distributor/orders'
      path: '/distributor/orders'
      fullPath: '/distributor/orders'
      preLoaderRoute: typeof DistributorDistributorOrdersRouteImport
      parentRoute: typeof DistributorRouteRoute
    }
    '/_distributor/distributor/requests': {
      id: '/_distributor/distributor/requests'
      path: '/distributor/requests'
      fullPath: '/distributor/requests'
      preLoaderRoute: typeof DistributorDistributorRequestsRouteImport
      parentRoute: typeof DistributorRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCouponsRoute: typeof AuthenticatedAdminCouponsRoute
  AuthenticatedAdminCustomersRoute: typeof AuthenticatedAdminCustomersRoute
  AuthenticatedAdminDistributorsRoute: typeof AuthenticatedAdminDistributorsRoute
  AuthenticatedAdminInventoryRoute: typeof AuthenticatedAdminInventoryRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRoute
  AuthenticatedAdminProductsBoardRoute: typeof AuthenticatedAdminProductsBoardRoute
  AuthenticatedAdminReferralsRoute: typeof AuthenticatedAdminReferralsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCouponsRoute: AuthenticatedAdminCouponsRoute,
  AuthenticatedAdminCustomersRoute: AuthenticatedAdminCustomersRoute,
  AuthenticatedAdminDistributorsRoute: AuthenticatedAdminDistributorsRoute,
  AuthenticatedAdminInventoryRoute: AuthenticatedAdminInventoryRoute,
  AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRoute,
  AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRoute,
  AuthenticatedAdminProductsBoardRoute: AuthenticatedAdminProductsBoardRoute,
  AuthenticatedAdminReferralsRoute: AuthenticatedAdminReferralsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReferralsRoute: typeof AuthenticatedReferralsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReferralsRoute: AuthenticatedReferralsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface DistributorRouteRouteChildren {
  DistributorDistributorInventoryRoute: typeof DistributorDistributorInventoryRoute
  DistributorDistributorOrdersRoute: typeof DistributorDistributorOrdersRoute
  DistributorDistributorRequestsRoute: typeof DistributorDistributorRequestsRoute
  DistributorDistributorIndexRoute: typeof DistributorDistributorIndexRoute
}

const DistributorRouteRouteChildren: DistributorRouteRouteChildren = {
  DistributorDistributorInventoryRoute: DistributorDistributorInventoryRoute,
  DistributorDistributorOrdersRoute: DistributorDistributorOrdersRoute,
  DistributorDistributorRequestsRoute: DistributorDistributorRequestsRoute,
  DistributorDistributorIndexRoute: DistributorDistributorIndexRoute,
}

const DistributorRouteRouteWithChildren =
  DistributorRouteRoute._addFileChildren(DistributorRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  DistributorRouteRoute: DistributorRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ShopRoute: ShopRoute,
  SignupRoute: SignupRoute,
  UpdatePasswordRoute: UpdatePasswordRoute,
  OrderOrderNumberRoute: OrderOrderNumberRoute,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
