// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

type SupabaseRuntimeConfig = {
  url?: string;
  publishableKey?: string;
};

declare global {
  interface Window {
    __SUPABASE_CONFIG__?: SupabaseRuntimeConfig;
  }
}

let runtimeConfig: SupabaseRuntimeConfig = {};

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

export function setSupabaseRuntimeConfig(config: SupabaseRuntimeConfig) {
  runtimeConfig = config;
  if (typeof window !== "undefined") window.__SUPABASE_CONFIG__ = config;
}

export function hasSupabaseConfig() {
  const metaEnv = import.meta.env as Record<string, string | undefined>;
  const processEnv = typeof process !== "undefined" ? process.env : undefined;
  const browserConfig = typeof window !== "undefined" ? window.__SUPABASE_CONFIG__ : undefined;
  return Boolean(
    metaEnv.VITE_SUPABASE_URL ||
      runtimeConfig.url ||
      browserConfig?.url ||
      processEnv?.SUPABASE_URL,
  ) && Boolean(
    metaEnv.VITE_SUPABASE_PUBLISHABLE_KEY ||
      runtimeConfig.publishableKey ||
      browserConfig?.publishableKey ||
      processEnv?.SUPABASE_PUBLISHABLE_KEY,
  );
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const metaEnv = import.meta.env as Record<string, string | undefined>;
  const processEnv = typeof process !== "undefined" ? process.env : undefined;
  const browserConfig = typeof window !== "undefined" ? window.__SUPABASE_CONFIG__ : undefined;
  const SUPABASE_URL =
    metaEnv.VITE_SUPABASE_URL ||
    runtimeConfig.url ||
    browserConfig?.url ||
    processEnv?.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    metaEnv.VITE_SUPABASE_PUBLISHABLE_KEY ||
    runtimeConfig.publishableKey ||
    browserConfig?.publishableKey ||
    processEnv?.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
