// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fdxqhguolqrjbplkifgc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkeHFoZ3VvbHFyamJwbGtpZmdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM0NTEwMzcsImV4cCI6MjA5OTAyNzAzN30.qrvHcOMhsy8sB1WVZxUOVAmfhwpeRHRyiNuca0pjVi0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});